### ISSUE TITLE
ACLU website is down under load

### ISSUE THREAD

**Issue by craiggerz** [mcgd/project-ellis#10]
I'm sure they're working on it, but perhaps someone with AWS skills can offer assistance or a bridge temp site to allow continued donations?

**Comment by yousifa** [comment]
You have a contact there I can get in touch with?

**Comment by craiggerz** [comment]
Asking around. I know the advocacy people there, not the ops staff

**Comment by craiggerz** [comment]
Interstitial static page is up now

**Comment by yousifa** [comment]
If you find someone there and need help lmk
