### ISSUE TITLE
Hoping to touch base before leaving the country to renew expired passport

### ISSUE THREAD

**Issue by hochung** [mcgd/project-ellis#21]
I am currently a software engineer in the bay area on the OPT visa, and am going home to Hong Kong to renew my passport. Although I am not (yet) directly affected, I certainly feel very concerned about the recent executive order on immigration and possible upcoming H1B reform. So I would like to touch base with Project Ellis to understand any help/resource available should any new EO on these issues comes through in the near future when I am back home. Thank you.

**Comment by mcgd** [comment]
Hi @hochung -- I have a couple of referrals for you. All of these folks will be able to help and their fees are covered by project ellis (tell them to bill me). :)

Cedric Maximillian
Los Angeles | 8939 S. Sepulveda Blvd Suite 233 Los Angeles California 90045 | (310) 591-8200
Vancouver | #1105-8131 Nunavut Lane Vancouver B.C. V5X 0E2 | (604) 288-7771
Toll Free (888) 228-4525 | Facsimile (866) 882-8684
cedric@maxlawinc.com | www.maxlawinc.com

melaniekehr@josemarinlaw.com and 415.753.3539 (office phone). Tell her that your case is paid for by Project Ellis and use my name. She is SF based. 

Keep me posted please so we can reach out to others if needed. There is a whole community of people here who will rally around you!

**Comment by jcm2017** [comment]
@mcgd assuming it's ok to cut and paste this info when replying to anyone else with the same question?  thought i'd ask first before posting to this board incorrectly. :)

**Comment by mcgd** [comment]
Yes, absolutely @jcm2017

**Comment by hochung** [comment]
@mcgd Thanks so much for your generous help!

**Comment by lindseywig** [comment]
Hi @hochung, on behalf of Project Ellis, were you able to connect with Cedric or Melanie to answer your questions? If you had any complications or have more questions, please let us know.
