### ISSUE TITLE
Executive Order Updates from EIGLaw.com

### ISSUE THREAD

**Issue by pjmodi** [mcgd/project-ellis#22]
We are receiving updates from our legal counsel, which I will share here (with permission).

**Comment by pjmodi** [comment]
`Mon, Jan 30, 2017 at 1:55 PM`

As the last 72 hours have been a whirlwind with regards to the new administration’s Executive Order on immigration, we wanted to take a brief breath and update you since the last EIG Dispatch/communication from the firm.
 
As a reminder, a summary of the EO is below:
 
·       Refugee Admissions: Stop most refugee admissions for at least 120 days, with exceptions permitted for those fleeing religious persecution if their religion is a minority in their country of nationality. Reduce refugee admissions for FY2017 to 50,000 from President Obama's goal of 110,000.
·       Ban on Entry to U.S. for Certain Countries: Ban on entry for at least 90 days of all immigrants and nonimmigrants for designated countries, for nationals of Iran, Iraq, Libya, Somalia, Sudan, Syria, and Yemen. Other countries may be added, and adjudications of other immigration benefits could be impacted. After 90 days, travel is not automatically reinstated. Instead, DHS is required to report whether countries have provided information "needed … for the adjudication of any … benefit under the INA … to determine that the individual seeking the benefit is who the individual claims to be and is not a security or public-safety threat." If not, the country would have 60 days to comply, or the travel ban would become indefinite.
·       Screening for All Immigration Benefits: Add requirements to screenings and procedures for all immigration benefits to identify fraud and detect intent to do harm. Can also look at whether someone will contribute to society or the national interest.
·       Biometric Entry-Exit System: Direct agencies to expedite completion of biometric entry-exit system.
·       Suspends the Visa Interview Waiver Program: All visa applicants will be required to attend an interview unless not required by statute. This ends the “dropbox” service utilized at several US Embassies around the world.
  
We have included 3 examples to illustrate who IS and who IS NOT subject to the 90 day ban.
 
Example 1: A citizen of Iran, Iraq, Libya, Somalia, Sudan, Syria, or Yemen with a valid visa to the US would not be able to enter the country. Airlines are preventing these individuals from boarding planes flying to the U.S.
 
Example 2: A dual national of one of the banned countries (Iran, Iraq, Libya, Somalia, Sudan, Syria, or Yemen) and another country (e.g. France), may be barred from entering the US on a valid work visa (such as a TN or L-1 visa). As of this morning, it was confirmed that foreign nationals possessing a UK or Canadian passport (but were born in 1 of the 7 banned countries) would be allowed to enter the U.S. on the UK or Canadian passport, provided that they possess a valid visa. This situation is fluid and we will update you as U.S. Customs clarifies the situation with additional countries.
 
Example 3: A United States green card holder (permanent resident) who was born in Iran, Iraq, Libya, Somalia, Sudan, Syria, or Yemen is NOT subject to the ban. The U.S. Department of Homeland Security clarified this issue last night at approximately 7 pm EST.
 
As the situation is fluid with the immigration Executive Orders, we will be monitoring the above events and update you accordingly.  We will also be sending around an FAQ shortly to address commonly asked questions about the Order.

**Comment by pjmodi** [comment]
`Tue, Jan 31, 2017 at 8:52 AM`

I’m writing with a few updates from the last 12 hours and to provide an FAQ, attached.
 
1). It is being confirmed that dual nationals with an Australian passport are exempt from the travel ban (in the event that they were born in 1 of the 7 banned countries).  This was reported last evening around 7 pm EST.
 
2). EIG has reached out to a few U.S. Embassies in India and have confirmed that the visa interview waiver program is still in place. Individuals can continue to use the dropbox service (for now), but may be called in for an interview, as the service will likely cease in the upcoming days or weeks.
 
3). In an unconfirmed report, the USCIS is ceasing adjudication on green card and citizenship applications for individuals who were born in 1 of the 7 banned countries.  Applications will be “frozen” until the ban is over. We will confirm once we have an official statement from USCIS.
 
4). The acting U.S. Attorney General, Sally Yates, was relieved of her duties last night after stating she would not defend the travel ban in Federal Court amongst the myriad of lawsuits filed in the past 4 days.  Dana J. Boente was named as her successor until a permanent U.S. Attorney General is confirmed.

**Comment by shripriyam** [comment]
Thank you for the updates, @pjmodi

**Comment by pjmodi** [comment]
`Wed, Feb 1, 2017 at 10:12 AM`

A few recent updates on the Executive Order as the dust begins to settle:

1. U.S. Customs clarified yesterday that in the case of dual nationals, they will treat nationality according to the [travel document](https://www.cbp.gov/border-security/protecting-nation-foreign-terrorist-entry-united-states) presented at the port of entry. The FAQs have been updated accordingly to read as follows:

> Q: I am a dual national of 1 of the 7 listed countries and another country, am I barred from entering the U.S.?
>  
> A: If you were born in 1 of the 7 banned countries and are also a citizen of another country, you will be treated according to the travel document that you present at the point of entry.
> 
> For example, an Iranian national with a Canadian passport would be treated as a Canadian national if she presents her Canadian passport (not her Iranian passport) at the point of entry. Similarly, an Iraqi national with a German passport would be treated as a German national if he presents his German passport at the point of entry.


2. U.S. Customs clarified that green card holders from 1 of the 7 banned countries will continue to have their citizenship applications processed by the USCIS. The USCIS has not clarified if the EO will or will not impact pending visa extensions, new visa applications (change of status applications filed with the USCIS), work authorization applications, or green card applications for individuals from 1 of the 7 banned countries. The FAQs have been amended as follows:
 

> **Q: I am in the U.S. and have my U.S. citizenship in process. Should I expect any delays to my application?**
> 
> A: No. USCIS has confirmed that they will continue to adjudicate N-400 applications for naturalization and administer the oath of citizenship consistent with prior practices.

 
3. A new immigration Executive Order was [leaked](http://apps.washingtonpost.com/g/documents/national/draft-executive-orders-on-immigration/2315/) last night, entitled “Protecting Taxpayer Resources by Ensuring Our Immigration Laws Promote Accountability and Responsibility.” The purpose of the Order is to deny admission to any alien who has become a public charge or “identify and remove” and alien who has become a public charge and is subject to removal. This Executive Order is aimed at individuals who have accepted public assistance from the U.S. government, and we do not foresee that it will impact your employees currently on work visas.

**Comment by pjmodi** [comment]
**Fri, Feb 3, 2017 at 2:55 PM**

Today, it was [reported](https://www.nytimes.com/2017/02/03/us/visa-ban-legal-challenge.html) that visas have been cancelled for nationals from the 7 banned countries pursuant to the recent Executive Order (EO). However, it was not clear if the revocations impact the immigration status for nationals from the 7 banned countries who are currently residing in the US.  The initial understanding was that no further visas would be issued based on the EO, but the status of individuals currently in the US would not be impacted.
 
The news that came out today indicated that anywhere from 60,000 to 100,000 visas have been revoked.  Specifically, we understand that the visas were revoked by the Department of State (DOS) for nationals located in the US and abroad from the 7 banned countries.
 
In our view, the DOS is only responsible for the issuance of visas, while the Department of Homeland Security (DHS) is responsible for an individual’s immigration status in the US.  Since only the DOS has revoked visas, we believe that only the visa (i.e. visa stamp in the passport) has been cancelled, but that the individual’s immigration status in the US remains valid.
 
To further our view, we have not received any notice from DHS that the immigration status of anyone has been cancelled as a result of the EO.  As the attorney of record, we should be notified of any action taken our client’s cases.
 
We will continue to monitor this matter closely and notify you of any updates. However, if you receive any questions or concerns from an individual in the US, we have no information indicating that their immigration status has been cancelled or revoked.  However, our previous guidance does stand that any national from 1 of the 7 banned countries should not travel outside of the US at this time.

**Comment by pjmodi** [comment]
Closing this out for the revised Executive Order (2.0?).
